# The following two functions calculate the inverse of a matrix.
# Caching is being used to speed up the process: if inverse has 
# already been calculated previously, the result will be returned 
# using the stored value instead of doing the calculation again. 

#makeCacheMatrix creates a special "vector", which is a list containing a function to
# set and get value of matrix and 
# set and get value of inverse of a matrix

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setmatrix <- function(solve) m <<- solve
  getmatrix <- function() m
  list(set = set, get = get,
       setmatrix = setmatrix,
       getmatrix = getmatrix)
}

# cacheSolve() calculates the inverse of the list generated by makeCacheMatrix()
# First cacheSolve() checks if the inverse has already been calculated. 
# If so, it gets the inverse from the cache and skips the computation. 
# Otherwise, it calculates the inverse of the matrix.

cacheSolve <- function(x=matrix(), ...) {
  m <- x$getmatrix()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data<- x$get()
  m <- solve(data, ...)
  x$setmatrix(m)
  m
}
